version: 2

before:
  hooks:
    - go mod tidy

builds:
  - dir: ./cmd/goverseer
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/simplifi/goverseer/internal/goverseer/version.Version={{.Version}}
    targets:
      - go_first_class

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
